name: inception

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress

networks:
  inception:
    name: inception

volumes:
  mariadb_volume:
    name: "mariadb_volume"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jfrancis/data/mariadb
  wordpress_volume:
    name: "wordpress_volume"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jfrancis/data/wordpress